FROM node:24 AS build

WORKDIR /app

COPY ../../frontend/package*.json ./

RUN npm install

COPY ../../frontend .

RUN npm run build

FROM nginx:1
COPY --from=build /app/dist/ /usr/share/nginx/html
COPY ../../infra/nginx/nginx.conf /etc/nginx/conf.d/default.conf
